development: &default
  contentful_access_token: 2bb89d30ee7a79b5d59a163b6069b052f2461b5688cf9c7ab00f725bcf402397
  contentful_space: ti1zf61egylr
  contentful_default_locale: 'en-US'
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_db: 0

test:
  <<: *default
  redis_db: 10

